Add missing <io.h> for '_get_osfhandle'.
First detected in https://github.com/microsoft/vcpkg/pull/33088

```
D:\buildtrees\openslide\src\v3.4.1-a70eeb2621.clean\test\test-common.c(51,25): error: call to undeclared function '_get_osfhandle'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  HANDLE hdl = (HANDLE) _get_osfhandle(fd);
```

Signed-off-by: Billy Robert O'Neal III <bion@microsoft.com>