trestle: fix compile warning with libtiff 4.5.0
libtiff 4.5.0 changes tdir_t from uint16_t to uint32_t, causing this
warning:

    src/openslide-vendor-trestle.c: In function 'trestle_open':
    src/openslide-vendor-trestle.c:324:13: error: comparison of integer expressions of different signedness: 'tdir_t' {aka 'unsigned int'} and 'int32_t' {aka 'int'} [-Werror=sign-compare]
      324 |     if (dir < overlap_count) {

overlap_count doesn't ever store a negative value, so make it unsigned.

Signed-off-by: Benjamin Gilbert <bgilbert@cs.cmu.edu>